### ISSUE TITLE
Update crash

### ISSUE THREAD

**Issue by Jocky69** [VaporeonScripts/NeoTech-Reborn#1]
Hi. Every time i do an update from curse, I got an installation crash and all the files in folders are deleted.. When i update from curseforge website, it install a new instance.

**Comment by VaporeonScripts** [comment]
Strange,I'll have to check that personally

**Comment by Jocky69** [comment]
Thanks.

**Comment by Jocky69** [comment]
Love the modpack so far.

**Comment by VaporeonScripts** [comment]
Ty,ill see what I can do to fix the problem 😁

**Comment by Jocky69** [comment]
Can you tell me where to reenable bookmarks?

**Comment by VaporeonScripts** [comment]
Sure,config,jei client,find any trace of bookmark and put the default value that it say after #

**Comment by Jocky69** [comment]
I'm looking at it right now.

**Comment by VaporeonScripts** [comment]
Later,before ⚒️,I can send U pics of where to go if ur unable to find it

**Comment by Jocky69** [comment]
i'm testing it right now

**Comment by Jocky69** [comment]
I need a hint , it doesn't seems to be the good one.

**Comment by Jocky69** [comment]
testing something else

**Comment by Jocky69** [comment]
i reenabled the bookmarks and change the column and row size. Now it's ok. Just waiting if you find the problem of updating.
Thanks for your help.

**Comment by VaporeonScripts** [comment]
alright,ima check it out today

**Comment by Jocky69** [comment]
Just to know. What is your time right now?

**Comment by VaporeonScripts** [comment]
7.12 am

**Comment by Jocky69** [comment]
ok, here is 1h13 am

**Comment by Jocky69** [comment]
I'm going to sleep. Have a nice day.

**Comment by VaporeonScripts** [comment]
Do u use prism launcher or curseforge launcher

**Comment by Jocky69** [comment]
curseforge. I don't know prism.

**Comment by VaporeonScripts** [comment]
Alright

**Comment by Jocky69** [comment]
Unfortunately not. :( 
I'm gonna reinstall a fresh installation with the latest version. Had to restart a new game anyway. I'll check on a another update. By the way, just to let you know that i had a few other mod. You may check if it's cause by one. I always play with those mods without problems.

advanced-xray-neoforge-21.0.0
inventoryhud.neoforged.1.21-3.4.26
SimpleBackups-1.21-4.0.6
Xaeros_Minimap_24.5.0_NeoForge_1.21
XaerosWorldMap_1.39.0_NeoForge_1.21

**Comment by VaporeonScripts** [comment]
why would u use xaero mods if ftb chunks is in the pack? it includes both minimap and worldmap, the minimap is just disabled but u can enable it by clicking M, clicking the gear in the bottom left,and enabling minimap

**Comment by VaporeonScripts** [comment]
kinda sure they dont cause issues

**Comment by VaporeonScripts** [comment]
also why do u use xray lmao :sob: ,finding ores its the easiest part

**Comment by Jocky69** [comment]
Xaero's is more complete. I use it for years. For xray, it's not as important. I just want to be sure that they don't cause problem. And i'm sure that i'm not the only one using it.

**Comment by VaporeonScripts** [comment]
alright

**Comment by Jocky69** [comment]
the game crash at loading.

[crash-2024-10-21_14.13.36-client.txt](https://github.com/user-attachments/files/17465279/crash-2024-10-21_14.13.36-client.txt)

**Comment by Jocky69** [comment]
i tried loading the game without Xaero's minimap and worldmap and still crashing.

[crash-2024-10-21_14.10.14-client.txt](https://github.com/user-attachments/files/17465362/crash-2024-10-21_14.10.14-client.txt)

**Comment by Jocky69** [comment]
i deleted the modpack and will start it without any other mods.

**Comment by Jocky69** [comment]
I'm desperate. The game crash with a fresh install without any changes.

**Comment by VaporeonScripts** [comment]
try to start it again,sometimes it may crash due to it being new xD, happens to me too sometimes,i just relaunch it

**Comment by Jocky69** [comment]
i did it 3 times. I just reinstalled it now to see.

**Comment by VaporeonScripts** [comment]
if it does still happen,could u try using prism launcher,for me and other users the pack just works fine, also after 9.0 update, prism launcher became so good fr

**Comment by Jocky69** [comment]
Where do i find it?

**Comment by Jocky69** [comment]
I found prism

**Comment by Jocky69** [comment]
i got a Windows message ^^ 

Windows protected your PC
Microsoft Defender SmartScreen prevented an unrecognized app from starting. Running this app might put your PC at risk.

**Comment by Jocky69** [comment]
I tried to install from the zip files, but says that i need to download manually some mods.

**Comment by VaporeonScripts** [comment]
may u show the pic? ill guide u through that

**Comment by VaporeonScripts** [comment]
also, would be easier for me if u contacted me with discord, from my server,as i got it always opened,while i open occasionally github (like when needed)

**Comment by Jocky69** [comment]
I'm gonna stop for now. Anything i tried didn't work.

**Comment by VaporeonScripts** [comment]
Just use prism launcher,it will work

**Comment by Jocky69** [comment]
i tried it but can't get the modpack to install

**Comment by VaporeonScripts** [comment]
Why do you have all the problems in this world😭may U record a video of steps U do?

**Comment by Jocky69** [comment]
And i'm a little old man. Can you just tell me the first step to install the modpack please.

**Comment by VaporeonScripts** [comment]
Well,to install it U could download the file from cf site,click import ,select it,and should do stuff,either that or from the app,U can search for the modpack there and install it

**Comment by Jocky69** [comment]
FarmersStructures-1.0.1-1.21.jar: https://www.curseforge.com/minecraft/mc-mods/farmers-structures/download/5665112 
Hash: e0b8ba6477d9bacb1798be78798245790d762f70 ✘ Not Found 

and some others too :( weird

**Comment by VaporeonScripts** [comment]
What launcher did U use when it showed that

**Comment by Jocky69** [comment]
I'm surely the only one having those problems. I'm maybe old but not stupid. But now i feel like it.

**Comment by Jocky69** [comment]
prism

**Comment by VaporeonScripts** [comment]
If it's prism ,that's normal ,click open all,download them all in download directory,then see if it's all green,next click continue ,it will install them

**Comment by Jocky69** [comment]
ok i'll try.

**Comment by Jocky69** [comment]
It's downloading libraries.

**Comment by Jocky69** [comment]
35% Takes long. Probably files needed the first time.

**Comment by Jocky69** [comment]
the game crash at loading. I'm cursed.

**Comment by Jocky69** [comment]
Ok for me for today. Goodnight.

**Comment by VaporeonScripts** [comment]
Try to allocate more ram

**Comment by Jocky69** [comment]
i already have 12 gigs of ram. I put 16 gigs for the modpack and still have this screen for at least 10 mins
![Loading](https://github.com/user-attachments/assets/f866ea40-b599-4588-b04a-ce01d7e0244d)
.

**Comment by VaporeonScripts** [comment]
only 8.5gb are required for the pack....

**Comment by VaporeonScripts** [comment]
anyways soon im dropping a massive update, maybe that will fix it

**Comment by Jocky69** [comment]
I did it with a fresh install and same thing 3 times. 
I always use 12 gigs for all mod packs without any problems.

**Comment by Jocky69** [comment]
Hope :)

**Comment by VaporeonScripts** [comment]
using too much ram will cause performance to be worse, 8.5gb is enough

**Comment by Jocky69** [comment]
I tried with 8.5 gigs and same thing. I'll wait for the update.

**Comment by VaporeonScripts** [comment]
The update got released,only need to wait for curseforge to approve it

**Comment by VaporeonScripts** [comment]
the update is out, please try it if you can

**Comment by Jocky69** [comment]
When updating i got this message
![Crash when updating](https://github.com/user-attachments/assets/39945d41-145d-4ebb-beee-c8661ccaa834)

**Comment by Jocky69** [comment]
i deleted the modpack and reinstall the latest version

**Comment by Jocky69** [comment]
i tried with Prism and crash too

**Comment by Jocky69** [comment]
It's probably a stupid thing from my side, but what is it :(

**Comment by VaporeonScripts** [comment]
send the mclo.gs link....

**Comment by Jocky69** [comment]
https://mclo.gs/fBMY0n1

**Comment by VaporeonScripts** [comment]
Provide latest.log

**Comment by VaporeonScripts** [comment]
Always on mclo.gs

**Comment by Jocky69** [comment]
https://mclo.gs/ZLfAkwb

**Comment by VaporeonScripts** [comment]
![Screenshot_20241022-215640_Brave](https://github.com/user-attachments/assets/067e755d-2aa5-4658-b281-fa057832703e)
U were crashing cuz ur using windows lel,windows being windows,the dev is gonna fix it😄

**Comment by VaporeonScripts** [comment]
Configurable mod

**Comment by VaporeonScripts** [comment]
Delete configurable and try this one: https://maven.bawnorton.com/releases/com/bawnorton/configurable/configurable-neoforge-yarn/2.1.3+1.21.1/configurable-neoforge-yarn-2.1.3+1.21.1.jar

**Comment by VaporeonScripts** [comment]
Also consider dming me on discord (natsuyami_xfx) because it's easier for me to reply and help

**Comment by Jocky69** [comment]
Last message for now. With the change of Configurable-neoforge-yarn-2.1.3+1.21.1 and removing SimpleBackups-1.21-4.0.7 that i found out was making the loading freeze, everything is working great. Thanks for your help.

**Comment by VaporeonScripts** [comment]
Finally,no problem 😁

**Comment by Jocky69** [comment]
Is it only me but i can't find any osmium

**Comment by VaporeonScripts** [comment]
from which mod is that?

**Comment by Jocky69** [comment]
Mekanism

**Comment by VaporeonScripts** [comment]
ima see what i can do

**Comment by VaporeonScripts** [comment]
for further questions, please join the server because this issue is fixed:
https://discord.gg/8Hz9qTjJaB

**Comment by Jocky69** [comment]
It says the invite is invalid
