### ISSUE TITLE
Bugs  with W-A-D-S keybind

### ISSUE THREAD

**Issue by Jocky69** [VaporeonScripts/NeoTech-Reborn#2]
When i press W-A-D-S, to search for an item in chest, backpack, my player is moving.

**Comment by VaporeonScripts** [comment]
That's not a bug,it's a feature from invmove

**Comment by Jocky69** [comment]
Can i remove it? For me it's anoying.

**Comment by VaporeonScripts** [comment]
Ofc you can

**Comment by Jocky69** [comment]
;)

**Comment by VaporeonScripts** [comment]
The issue seems solved,goodbye
