### ISSUE TITLE
Prefab softlock

### ISSUE THREAD

**Issue by Pumatyger** [VaporeonScripts/NeoTech-Reborn#4]
When trying to change the housetype in prefab minecraft softlocks.

**Comment by Pumatyger** [comment]
[logs.zip](https://github.com/user-attachments/files/18229337/logs.zip)
logs

**Comment by VaporeonScripts** [comment]
Mind uploading that on mclo.gs

**Comment by Pumatyger** [comment]
https://mclo.gs/BoQmb4p

https://mclo.gs/igVqqgD

**Comment by VaporeonScripts** [comment]
reported those to prefab github, will see how it goes

**Comment by VaporeonScripts** [comment]
https://github.com/Brian-Wuest/MC-Prefab/issues/299

are u using java 21?

**Comment by VaporeonScripts** [comment]
cuz it looks like ur not, use java 21 for the server

**Comment by VaporeonScripts** [comment]
Closing the issue due to inactivity and probably ur own issue,caused by mismatched Java version
